version: "3.3"
services:
  sabnzbd:
      container_name: "sabnzbd"
      image: "linuxserver/sabnzbd"
      volumes:
        - /sabnzb/config:/config
        - type: volume
          source: sabnzb
          target: /mnt/sabnzb
        - type: volume
          source: Movies
          target: /mnt/Movies
      networks:
        L2Net:
          ipv4_address: 10.0.0.15
      environment:
        - PUID=0
        - PGID=0
      restart: always

  sonarr:
      container_name: "sonarr"
      image: "linuxserver/sonarr"
      ports:
        - 8989:8989
      volumes:
        - /sonarr/config:/config
        - type: volume
          source: TV-Shows
          target: /mnt/TV-Shows
        - type: volume
          source: TV-Shows1
          target: /mnt/TV-Shows1
        - type: volume
          source: sabnzb
          target: /mnt/sabnzb
      environment:
        - PUID=568
        - PGID=100
      restart: always

  radarr:
      container_name: "radarr"
      image: "linuxserver/radarr"
      ports:
        - 7878:7878
      volumes:
        - /radarr/config:/config
        - type: volume
          source: Movies
          target: /mnt/Movies
        - type: volume
          source: sabnzb
          target: /mnt/sabnzb
      environment:
        - PUID=568
        - PGID=100
      restart: always

  readarr:
      container_name: "readarr"
      image: "linuxserver/readarr"
      networks:
        L2Net:
          ipv4_address: 10.0.0.16
      volumes:
        - /readarr/config:/config
        - type: volume
          source: Movies
          target: /mnt/Movies
        - type: volume
          source: sabnzb
          target: /mnt/sabnzb
      environment:
        - PUID=568
        - PGID=100
      restart: always

  smokeping:
    container_name: smokeping
    image: lscr.io/linuxserver/smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Chicago"
    volumes:
      - /smokeping-config:/config
      - /smokeping-data:/data
    restart: always
    networks:
      L2Net:
        ipv4_address: 10.0.0.14

volumes:
  Movies:
    driver_opts:
      type: "nfs"
      o: "addr=synology0,nolock,soft,rw"
      device: ":/volume1/Movies"

  TV-Shows:
    driver_opts:
      type: "nfs"
      o: "addr=synology0,nolock,soft,rw"
      device: ":/volume1/TV-Shows"

  TV-Shows1:
    driver_opts:
      type: "nfs"
      o: "addr=synology0,nolock,soft,rw"
      device: ":/volume1/TV-Shows1"

  sabnzb:
    driver_opts:
      type: "nfs"
      o: "addr=synology0,nolock,soft,rw"
      device: ":/volume1/sabnzb"

networks:
    L2Net:
       driver: ipvlan
       driver_opts:
          parent: ens192
          ipvlan_mode: l2
       ipam:
         config:
            - subnet: 10.0.0.0/16
