version: "3.3"
services:
  d0p1:
    container_name: "d0p1"
    image: "plexinc/pms-docker"
    networks:
      L2Net:
        ipv4_address: 10.0.0.110
    volumes:
        - /plex1/config:/config
        - type: volume
          source: Movies
          target: /mnt/Movies
          volume:
             nocopy: true
        - type: volume
          source: TV-Shows
          target: /mnt/TV-Shows
          volume:
             nocopy: true
        - type: volume
          source: TV-Shows1
          target: /mnt/TV-Shows1
          volume:
             nocopy: true
        - type: volume
          source: sabnzb
          target: /mnt/sabnzb
          volume:
             nocopy: true
    environment:
        - PUID=568
        - PGID=100
        - PLEX_CLAIM=claim-BKaBwYE3Es_wgRZy9PAU
    restart: always

  sabnzbd:
      container_name: "sabnzbd"
      image: "linuxserver/sabnzbd"
      ports:
        - 8080:8080
      volumes:
        - /sabnzb/config:/config
        - type: volume
          source: sabnzb
          target: /mnt/sabnzb
        - type: volume
          source: Movies
          target: /mnt/Movies
      environment:
        - PUID=0
        - PGID=0
      restart: always

  sonarr:
      container_name: "sonarr"
      image: "linuxserver/sonarr"
      ports:
        - 8989:8989
      volumes:
        - /sonarr/config:/config
        - type: volume
          source: TV-Shows
          target: /mnt/TV-Shows
        - type: volume
          source: TV-Shows1
          target: /mnt/TV-Shows1
        - type: volume
          source: sabnzb
          target: /mnt/sabnzb
      environment:
        - PUID=568
        - PGID=100
      restart: always

  radarr:
      container_name: "radarr"
      image: "linuxserver/radarr"
      ports:
        - 7878:7878
      volumes:
        - /radarr/config:/config
        - type: volume
          source: Movies
          target: /mnt/Movies
        - type: volume
          source: sabnzb
          target: /mnt/sabnzb
      environment:
        - PUID=568
        - PGID=100
      restart: always

  gozznet:
    container_name: gozznet
    image: mgossman71/gozznet-old:17.5
    networks:
      L2Net:
        ipv4_address: 10.0.0.13

volumes:
  Movies:
    driver_opts:
      type: "nfs"
      o: "addr=synology0,nolock,soft,rw"
      device: ":/volume1/Movies"

  TV-Shows:
    driver_opts:
      type: "nfs"
      o: "addr=synology0,nolock,soft,rw"
      device: ":/volume1/TV-Shows"

  TV-Shows1:
    driver_opts:
      type: "nfs"
      o: "addr=synology0,nolock,soft,rw"
      device: ":/volume1/TV-Shows1"

  sabnzb:
    driver_opts:
      type: "nfs"
      o: "addr=synology0,nolock,soft,rw"
      device: ":/volume1/sabnzb"

networks:
    L2Net:
       driver: ipvlan
       driver_opts:
          parent: ens192
          ipvlan_mode: l2
       ipam:
         config:
            - subnet: 10.0.0.0/16
    L3Net:
       driver: ipvlan
       driver_opts:
          parent: ens160
          ipvlan_mode: l3
       ipam:
          config:
             - subnet: 192.168.0.0/24
