version: "3.3"
services:
  d0p1:
    container_name: "d0p1"
    image: "plexinc/pms-docker"
    networks:
      L2Net:
        ipv4_address: 10.0.0.110
    volumes:
        - /plex1/config:/config
        - type: volume
          source: Movies
          target: /mnt/Movies
          volume:
             nocopy: true
        - type: volume
          source: TV-Shows
          target: /mnt/TV-Shows
          volume:
             nocopy: true
        - type: volume
          source: TV-Shows1
          target: /mnt/TV-Shows1
          volume:
             nocopy: true
        - type: volume
          source: sabnzb
          target: /mnt/sabnzb
          volume:
             nocopy: true
    environment:
        - PUID=568
        - PGID=100
        - PLEX_CLAIM=claim-BKaBwYE3Es_wgRZy9PAU
    restart: always

  gozznet:
    container_name: gozznet
    image: mgossman71/gozznet-old:17.5
    networks:
      L2Net:
        ipv4_address: 10.0.0.13
        
volumes:
  Movies:
    driver_opts:
      type: "nfs"
      o: "addr=synology0,nolock,soft,rw"
      device: ":/volume1/Movies"

  TV-Shows:
    driver_opts:
      type: "nfs"
      o: "addr=synology0,nolock,soft,rw"
      device: ":/volume1/TV-Shows"

  TV-Shows1:
    driver_opts:
      type: "nfs"
      o: "addr=synology0,nolock,soft,rw"
      device: ":/volume1/TV-Shows1"

  sabnzb:
    driver_opts:
      type: "nfs"
      o: "addr=synology0,nolock,soft,rw"
      device: ":/volume1/sabnzb"

networks:
    L2Net:
       driver: ipvlan
       driver_opts:
          parent: ens34
          ipvlan_mode: l2
       ipam:
         config:
            - subnet: 10.0.0.0/16
