version: "3.3"
services:
  plex:
    container_name: "plex"
    image: "plexinc/pms-docker"
    volumes:
        - /plex/config:/config
        - type: volume
          source: Movies
          target: /mnt/Movies
          volume:
             nocopy: true
        - type: volume
          source: TV-Shows
          target: /mnt/TV-Shows
          volume:
             nocopy: true
        - type: volume
          source: TV-Shows1
          target: /mnt/TV-Shows1
          volume:
             nocopy: true
        - type: volume
          source: sabnzb
          target: /mnt/sabnzb
          volume:
             nocopy: true
    environment:
        - PUID=568
        - PGID=100
        - PLEX_CLAIM=claim-UZXLzVxFDs9xPa1727BH
    ports:
      - 32400:32400
    restart: always
  smokeping:
    container_name: smokeping
    image: lscr.io/linuxserver/smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /smokeping-config:/config
      - /smokeping-data:/data
    restart: always
    ports:
      - 8081:80

  overseerr:
     container_name: "overseerr"
     image: sctx/overseerr:latest
     ports:
      - 5055:5055
     volumes:
      - /overseerr/config:/app/config
     logging:
       driver: json-file
       options:
         max-size: "10mb"
         max-file: "1"
     environment:
      - PUID=0
      - PGID=0
     restart: always

volumes:
  Movies:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.241,nolock,soft,rw"
      device: ":/volume1/Movies"

  TV-Shows:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.241,nolock,soft,rw"
      device: ":/volume1/TV-Shows"

  TV-Shows1:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.241,nolock,soft,rw"
      device: ":/volume1/TV-Shows1"

  sabnzb:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.241,nolock,soft,rw"
      device: ":/volume1/sabnzb"

  transmission:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.241,nolock,soft,rw"
      device: ":/volume1/sabnzb/transmission"

networks:
    L2Net:
       driver: ipvlan
       driver_opts:
          parent: eth1
          ipvlan_mode: l2
       ipam:
         config:
            - subnet: 10.0.0.0/16